# Generated by Django 2.2.3 on 2020-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200223_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pic/%Y%m%d/'),
        ),
    ]
